config/routes.rb
Rails.application.routes.draw do

  namespace :dev do
    namespace :git do
      get "/" => "commands#status"
      get "status" => "commands#status"
      resource :branch, only: [:create, :show, :destroy]
      resources :commits, only: :create
      post "commits/stash"
      get "commits/push"
      get "commits/pull"
      get "commits/add"
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dev/git/branches_controller.rb
class Dev::Git::BranchesController < ApplicationController
  def create
    Dir.chdir(Rails.root) do
      if params[:commit_hash].present?
        `git checkout #{params[:commit_hash].strip.reverse.chomp("#").reverse}`
        `git checkout -b #{params[:name].parameterize}`
      else
        `git checkout -b #{params[:name].parameterize}`
      end

      redirect_to dev_git_url, notice: "Created branch #{params[:name]}."
    end
  end

  def show
    Dir.chdir(Rails.root) do
      `git checkout #{params[:name].parameterize}`
    end

    redirect_to dev_git_url, notice: "Switched to branch #{params[:name]}."
  end

  def destroy
    if params[:name].parameterize != "master"
      Dir.chdir(Rails.root) do
        `git branch -D #{params[:name].parameterize}`
      end

      redirect_to dev_git_url, notice: "Deleted branch #{params[:name]}."
    else
      redirect_to dev_git_url, alert: "It's not a great idea to delete the master branch. If you really want to, you're on your own!"
    end
  end
end

app/controllers/dev/git/commands_controller.rb
class Dev::Git::CommandsController < ApplicationController
  def status
    Dir.chdir(Rails.root) do
      @status = `git status`

      @current_branch = `git symbolic-ref --short HEAD`.chomp

      diff = `git diff`

      unless diff.blank?
        @diff_html = `diff2html --style=side --output=stdout`.
          gsub("<h1>Diff to HTML by <a href=\"https://github.com/rtfpessoa\">rtfpessoa</a></h1>", "").
          gsub("<a class=\"d2h-file-switch d2h-hide\">hide</a>", "").
          gsub("<a class=\"d2h-file-switch d2h-show\">show</a>", "")
      else
        @last_diff_html = `diff2html --style=line --output=stdout -- -M HEAD~1`.
          gsub("<h1>Diff to HTML by <a href=\"https://github.com/rtfpessoa\">rtfpessoa</a></h1>", "").
          gsub("<a class=\"d2h-file-switch d2h-hide\">hide</a>", "").
          gsub("<a class=\"d2h-file-switch d2h-show\">show</a>", "")

        @last_commit_message = `git log -1 --pretty=%B`
      end

      @branches = `git branch --sort=-committerdate`.split - ["*"]

      # @log = `git log --branches --remotes --tags --graph --oneline --decorate --pretty=format:"#%h %d %s - %cr"`

      @log_html = `git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --branches --remotes --tags | sh ansi2html.sh --bg=dark`
    end
  end
end

app/controllers/dev/git/commits_controller.rb
class Dev::Git::CommitsController < ApplicationController
  def create
    Dir.chdir(Rails.root) do
      `git add -A`
      `git commit -m "#{params[:title]}" -m "#{params[:description]}"`
    end

    redirect_to dev_git_url, notice: "Changed committed."
  end

  def stash
    Dir.chdir(Rails.root) do
      `git add -A`
      `git stash`
    end

    redirect_to dev_git_url, notice: "Changes discarded."
  end

  def push
    Dir.chdir(Rails.root) do
      @result = `git push`
    end

    redirect_to dev_git_url, notice: "Pushed to GitHub."
  end

  def pull
    Dir.chdir(Rails.root) do
      @result = `git pull`
    end

    redirect_to dev_git_url, notice: "Pulled from GitHub."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def variablize_branch_name(name)
    if valid_variable_name?(name)
      name
    elsif name.to_i.to_s == name
      name.to_i.humanize
    elsif name.to_f.to_s == name
      name.to_f.humanize
    else
      (name.to_f.humanize + " " + SecureRandom.hex(6))
    end.parameterize.underscore
  end

  def valid_variable_name?(var_name)
    Object.new.instance_variable_set ("@" + var_name).to_sym, nil
    true
  rescue NameError
    false
  end
end

app/views/dev/git/commands/log.html.erb
<div class="row mb-4">
  <div class="col">
    <div class="card">
      <h1 class="card-header">
        <% if @diff_html.present? %>
          On branch <code><%= @current_branch %></code>
        <% else %>
          <code>git status</code>
        <% end %>
      </h1>

      <div class="card-block">
        <% if @diff_html.present? %>
          <p class="h4 mb-3 text-center">
            You have changes
          </p>

          <iframe srcdoc="<%= @diff_html %>" width="100%" height="400" class="mb-3">
          </iframe>

          <p class="h4 mb-3 text-center">
            What do you want to do?
          </p>

          <div class="row">
            <div class="col">
              <div class="card">
                <div class="card-header h6">
                  Commit your changes to the current branch
                </div>

                <div class="card-block">

                  <%= form_tag dev_git_commits_url do %>
                    <div class="form-group">
                      <%= label_tag :title %>
                      <%= text_field_tag :title, nil, placeholder: "Enter a title for your commit (required)...", class: "form-control", required: true %>
                    </div>

                    <div class="form-group">
                      <%= label_tag :description %>
                      <%= text_area_tag :description, nil, placeholder: "Enter a longer description of your changes (optional)...", class: "form-control" %>
                    </div>

                    <%= button_tag "Commit to #{@current_branch}", class: "btn btn-primary btn-block" %>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="col">
              <div class="row mb-2">
                <div class="col">
                  <div class="card">
                    <div class="card-header h6">
                      Switch to a new branch
                    </div>

                    <div class="card-block">
                      <%= form_tag dev_git_branches_url, class: "full-width mb-2" do %>
                        <div class="form-group">
                          <%= label_tag :name, nil, class: "sr-only" %>
                          <%= text_field_tag :name, nil, placeholder: "Enter a name for the branch to create...", class: "form-control" %>
                        </div>
                        <%= button_tag "Create a new branch", class: "btn btn-success btn-block" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <div class="card">
                    <div class="card-header h6">
                      Discard your changes
                    </div>

                    <div class="card-block">
                      <%= button_to "Discard all changes", dev_git_commits_stash_url, class: "btn btn-danger btn-block", method: :post, data: { confirm: "Are you sure you want to discard these changes?" } %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        <% else %>

          <div class="row">
            <div class="col">
              <pre>
                <%= simple_format @status %>
              </pre>

              <%= link_to "git push", "#", class: "btn btn-primary btn-block" %>
            </div>

            <div class="col">
              <ul class="list-group">
                <li class="list-group-item list-group-item-success">
                  Create a new branch
                </li>

                <li class="list-group-item">
                  <%= form_tag dev_git_branches_url, class: "full-width mb-2" do %>
                  <div class="form-group">
                    <%= label_tag :name, nil, class: "sr-only" %>
                    <%= text_field_tag :name, nil, placeholder: "Enter a name for the branch to create...", class: "form-control" %>
                  </div>
                  <%= button_tag "Create a new branch", class: "btn btn-success btn-block" %>
                  <% end %>
                </li>

                <li class="list-group-item list-group-item-info">
                  Existing branches
                </li>

                <li class="list-group-item">
                  <pre>
                    <%= simple_format @branches %>
                  </pre>

                  <%= form_tag dev_git_branches_checkout_url, method: :get, class: "full-width mb-2" do %>
                    <div class="form-group">
                      <%= label_tag :name, nil, class: "sr-only" %>
                      <%= text_field_tag :name, nil, placeholder: "Enter the name of the branch to switch to...", class: "form-control" %>
                    </div>
                    <%= button_tag "Switch to branch", class: "btn btn-primary btn-block" %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
          <pre>
            <%= simple_format @log %>
          </pre>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row mb-4">
  <div class="col">
    <div class="card">
      <h2 class="card-header">
        Log
      </h2>

      <div class="card-block">
        <pre>
          <%= simple_format @log %>
        </pre>
      </div>
    </div>
  </div>
</div>

app/views/dev/git/commands/status.html.erb
<div class="row mb-4">
  <div class="col">
    <div class="card">
      <h1 class="card-header">
        <% if @diff_html.present? %>
          On branch <code><%= @current_branch %></code>
        <% else %>
          <code>git status</code>
        <% end %>
      </h1>

      <div class="card-block">
        <%# if false %>
        <% unless @status.include?("nothing to commit, working tree clean") %>
          <p class="h4 mb-3 text-center">
            You have changes
          </p>

          <% if @status.include?("untracked files") %>
            <pre>
              <%= simple_format @status.
                    gsub("(use \"git add <file>...\" to include in what will be committed)\n\n", "").
                    gsub("(use \"git add\" to track)\n", "")%>
            </pre>
          <% end %>

          <% if @diff_html.present? %>
            <iframe srcdoc="<%= @diff_html %>" width="100%" height="400" class="mb-3">
            </iframe>
          <% end %>

          <p class="h4 mb-3 text-center">
            What do you want to do?
          </p>

          <div class="row">
            <div class="col">
              <div class="card">
                <div class="card-header h6">
                  Commit your changes to the current branch
                </div>

                <div class="card-block">

                  <%= form_tag dev_git_commits_url do %>
                    <div class="form-group">
                      <%= label_tag :title %>
                      <%= text_field_tag :title, nil, placeholder: "Enter a title for your commit (required)...", class: "form-control", required: true, autofocus: true %>
                    </div>

                    <div class="form-group">
                      <%= label_tag :description %>
                      <%= text_area_tag :description, nil, placeholder: "Enter a longer description of your changes (optional)...", class: "form-control" %>
                    </div>

                    <%= button_tag class: "btn btn-primary btn-block", data: { toggle: "tooltip", html: true }, title: "<code>git add -A; git commit</code>" do %>
                      <%= octicon "git-commit", class: "mr-1" %>

                      Commit to <%= @current_branch %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="col">
              <div class="row mb-2">
                <div class="col">
                  <div class="card">
                    <div class="card-header h6">
                      Switch to a new branch
                    </div>

                    <div class="card-block">
                      <%= form_tag dev_git_branch_url, class: "full-width mb-2" do %>
                        <div class="form-group">
                          <%= label_tag :name, nil, class: "sr-only" %>
                          <%= text_field_tag :name, nil, placeholder: "Enter a name for the branch to create...", class: "form-control" %>
                        </div>
                        <%= button_tag class: "btn btn-success btn-block", data: { toggle: "tooltip", html: true }, title: "<code>git checkout -b [NEW BRANCH NAME]</code>" do %>

                          <%= octicon "git-branch", class: "mr-1" %>

                          Create a new branch
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <div class="card">
                    <div class="card-header h6">
                      Discard your changes
                    </div>

                    <div class="card-block">
                      <%= button_to dev_git_commits_stash_url, class: "btn btn-danger btn-block", method: :post, data: { confirm: "Are you sure you want to discard these changes?", toggle: "tooltip", html: true }, title: "<code>git add -A; git stash</code>" do %>
                        <%= octicon "trashcan", class: "mr-1" %>

                        Discard all changes
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        <% else %>

          <div class="row">
            <div class="col">
              <pre>
                <%= simple_format @status %>
              </pre>

              <%= link_to dev_git_commits_push_url, class: "btn btn-primary btn-block mb-4", data: { toggle: "tooltip", html: true }, title: "<code>git push</code>" do %>
                <%= octicon "repo-push", class: "mr-1" %>

                Push to GitHub
              <% end %>

              <% unless @current_branch == "master" %>
                <%= link_to "https://github.com/firstdraft/git_client_poc/compare/#{@current_branch}?expand=1", class: "btn btn-primary btn-block mb-4", target: "_blank" do %>
                  <%= octicon "git-pull-request", class: "mr-1" %>

                  Open a pull request into master
                <% end %>
              <% end %>

              <%= link_to dev_git_commits_pull_url, class: "btn btn-primary btn-block mb-4", data: { toggle: "tooltip", html: true }, title: "<code>git pull</code>" do %>
                <%= octicon "repo-pull", class: "mr-1" %>

                Pull from GitHub
              <% end %>

              <p>
                The last thing you did was:
              </p>

              <blockquote class="blockquote">
                <%= @last_commit_message %>
              </blockquote>

              <%= link_to "#latest_diff_html", class: "btn btn-secondary btn-block mb-4", data: { toggle: "collapse" }, title: "git show" do %>
                <%= octicon "eye", class: "mr-1" %>

                Show last commit
              <% end %>

              <div id="latest_diff_html" class="collapse">
                <iframe srcdoc="<%= @last_diff_html %>" width="100%" height="400" class="mb-3">
                </iframe>
              </div>
            </div>

            <div class="col">
              <ul class="list-group">
                <li class="list-group-item list-group-item-success">
                  New Branch
                </li>

                <li class="list-group-item">
                  <%= form_tag dev_git_branch_url, class: "full-width mb-2" do %>
                    <div class="form-group">
                      <%= label_tag :name, "Go ahead, experiment!" %>
                      <%= text_field_tag :name, nil, placeholder: "Enter a name for the new branch...", class: "form-control" %>
                    </div>
                    <%= button_tag class: "btn btn-success btn-block", data: { toggle: "tooltip", html: true }, title: "<code>git checkout -b [BRANCH NAME]</code>" do %>
                      <%= octicon "git-branch", class: "mr-1" %>

                      Create branch
                    <% end %>
                  <% end %>
                </li>

                <li class="list-group-item list-group-item-info">
                  Existing branches
                </li>

                <% @branches.each do |branch| %>
                  <li class="list-group-item  justify-content-between">
                    <%= branch %>

                    <div class="btn-group">
                      <%= link_to octicon("git-compare"), dev_git_branch_url(name: branch), class: "btn btn-primary btn-sm", title: "Switch to branch<br><code>git checkout #{branch}</code>", data: { toggle: "tooltip", html: true } %>

                      <%= link_to octicon("trashcan"), dev_git_branch_url(name: branch), method: :delete, class: "btn btn-warning btn-sm", data: { toggle: "tooltip", confirm: "Are you sure you want to delete #{branch}?" }, title: "Delete branch #{branch}" %>
                    </div>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row mb-4">
  <div class="col">
    <div class="card">
      <h2 class="card-header">
        History
      </h2>

      <div class="card-block">
        <p class="lead">Do you want to jump back in time and go down a different path?</p>
        <%= form_tag dev_git_branch_url do %>
          <div class="form-group">
            <%= label_tag :commit_hash, "Branch off of" %>
            <%= text_field_tag :commit_hash, nil, placeholder: "Enter the sequence of digits preceding the commit (it's \"hash\") that you want to branch off of...", class: "form-control" %>
          </div>

          <div class="form-group">
            <%= label_tag :name, "Branch name" %>
            <%= text_field_tag :name, nil, placeholder: "Enter a name for the new branch...", class: "form-control" %>
          </div>

          <% if @diff_html.present? %>
            <%= button_tag "Can't go back in time while you have pending changes. Commit or discard them first.", class: "btn btn-primary btn-block", disabled: true %>
          <% else %>
            <%= button_tag class: "btn btn-success btn-block", data: { toggle: "tooltip", html: true }, title: "<code>git checkout [OLD HASH]; git checkout -b [NEW BRANCH NAME]</code>" do %>
              <%= octicon "git-branch", class: "mr-1" %>

              Create a new branch off of previous commit
            <% end %>
          <% end %>
        <% end %>

        <pre>
          <%= simple_format @log %>
        </pre>

        <% if @log_html.present? %>
          <iframe srcdoc="<%= @log_html %>" width="100%" height="800" class="mb-3">
          </iframe>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitClient</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <% if notice.present? %>
    <div class="row">
      <div class="col">
        <div class="alert alert-dismissable alert-success">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= notice %>
        </div>
      </div>
    </div>
    <% end %>

    <% if alert.present? %>
    <div class="row">
      <div class="col">
        <div class="alert alert-dismissable alert-warning">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= alert %>
        </div>
      </div>
    </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>